### ISSUE TITLE
Configuring Basic Auth

### ISSUE THREAD

**Issue by gurrie** [PGBI/kong-dashboard#31]
Hi,

Firstly thank you for building a great tool! I am currently trying to configure basic auth but am currently unable to do so.

I have added the following config to the server section related to the admin port in kong

      auth_basic "Restricted";
      auth_basic_user_file security/htpasswd;

However when I try to log in I get the following error:

 Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<server>' is therefore not allowed access. The response had HTTP status code 401

I am however able to query the admin API using the basic auth credentials?

Any help would be greatly appreciated.

Regards
Brian

**Comment by PGBI** [comment]
This is due to CORS restriction. kong-dashboard is a client-side app, your browser is directly making requests to the kong admin API.

To do so, it first makes an OPTIONS request (aka "preflight request") to know if CORS is allowed (which is the case for Kong admin API). If the response does not contain the following header: "Access-Control-Allow-Origin: GET, HEAD, POST, PUT, DELETE" then your browser blocks the request.

The problem is that basic auth credentials are not passed a preflight (see: https://www.google.fr/search?q=OPTIONS+request+Authorization+header ). And i believe your config is then blocking the preflight request. 

You should modify your config so that only non-preflight requests are protected with basic auth.
