### ISSUE TITLE
change primary color of materialize 

### ISSUE THREAD

**Issue by anirudhkkw** [PGBI/kong-dashboard#5]
Hi,

Any idea how I can change the primary color of materialize?? I want to do it through gulp JS

**Comment by PGBI** [comment]
You really don't like the colors :):) ?

Materialize will let you change primary colors here https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss

But right now, when building kong dashboard, the npm script does not compile materialize sass files but directly use the materialize default css file.

I'll need to allow overriding this _variables.scss file and compile materialize as well to be able to change primary colors.

**Comment by anirudhkkw** [comment]
I'm sorry but i really hate the colors :P 
so i found a work around.. 

gulpfile.js 

gulp.task('scss', function() {  
  return gulp.src(['./src/scss/app.scss']) 
      .pipe(sass())  // Compile sass
      .pipe(concat('materialize.min.css'))                               // Concat all css
      .pipe(minifyCss())                                         // Minify the CSS
      .pipe(gulp.dest('./public/css/'))                      // Set the destination to assets/css
});

src/scss/app.scss

$primary-color: #27beac;
@import './bower_components/Materialize/sass/materialize.scss'

that's it :) 


can i fork commit and send a pull req? :) 

also, amazing work !!! thank you so much for your time and effort :)

**Comment by PGBI** [comment]
I think you don't need to pipe materialize.min.css in your gulp function anymore.

But I get the idea. Feel free to submit a PR! A few things to think about:
- the content of src/less/app.less will need to be converted to sass,
- there are some places where I hardcoded the color (sorryyyy) (for instance, here https://github.com/PGBI/kong-dashboard/blob/master/src/less/app.less#L46 or there https://github.com/PGBI/kong-dashboard/blob/master/src/less/app.less#L102), it will need to be replaced by the proper sass variable.
- what would be nice is to have the custom colors defined in a separate file (like src/scss/custom_theme.scss) that would be git-ignored, so that people could modify it and not encounter merge conflicts when pulling the last version of kong dashboard.

**Comment by anirudhkkw** [comment]
submitted a pull request with all the changes you asked for :) please do review and tell me if i have to change anything.

**Comment by PGBI** [comment]
Closed with #6 

Thanks @anirudhkkw !
I added a slight modification to your PR: I removed the custom theme file from the git repository so that those who want to create this file won't have untracked git change.

So finally to be able to change the primary color, you need to create the file src/scss/_custom_theme.scss (the underscore is important, so that it's compiled before app.scss). 

Thanks again for you PR.

**Comment by anirudhkkw** [comment]
Thank you :)
